/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NilusRouteImport } from './routes/nilus'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsArchivedRouteImport } from './routes/settings.archived'
import { Route as NilusTasksRouteImport } from './routes/nilus.tasks'
import { Route as NilusSettingsRouteImport } from './routes/nilus.settings'
import { Route as NilusMemoryRouteImport } from './routes/nilus.memory'
import { Route as NilusEvidenceRouteImport } from './routes/nilus.evidence'
import { Route as NilusChatRouteImport } from './routes/nilus.chat'
import { Route as NilusChangesRouteImport } from './routes/nilus.changes'
import { Route as ChatLandingRouteImport } from './routes/chat.landing'
import { Route as ChatThreadIdRouteImport } from './routes/_chat.$threadId'
import { Route as NilusTasksTaskNumberRouteImport } from './routes/nilus.tasks.$taskNumber'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NilusRoute = NilusRouteImport.update({
  id: '/nilus',
  path: '/nilus',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRoute,
} as any)
const NilusTasksRoute = NilusTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => NilusRoute,
} as any)
const NilusSettingsRoute = NilusSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => NilusRoute,
} as any)
const NilusMemoryRoute = NilusMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => NilusRoute,
} as any)
const NilusEvidenceRoute = NilusEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => NilusRoute,
} as any)
const NilusChatRoute = NilusChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => NilusRoute,
} as any)
const NilusChangesRoute = NilusChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => NilusRoute,
} as any)
const ChatLandingRoute = ChatLandingRouteImport.update({
  id: '/chat/landing',
  path: '/chat/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)
const NilusTasksTaskNumberRoute = NilusTasksTaskNumberRouteImport.update({
  id: '/$taskNumber',
  path: '/$taskNumber',
  getParentRoute: () => NilusTasksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/nilus': typeof NilusRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/$threadId': typeof ChatThreadIdRoute
  '/chat/landing': typeof ChatLandingRoute
  '/nilus/changes': typeof NilusChangesRoute
  '/nilus/chat': typeof NilusChatRoute
  '/nilus/evidence': typeof NilusEvidenceRoute
  '/nilus/memory': typeof NilusMemoryRoute
  '/nilus/settings': typeof NilusSettingsRoute
  '/nilus/tasks': typeof NilusTasksRouteWithChildren
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/nilus/tasks/$taskNumber': typeof NilusTasksTaskNumberRoute
}
export interface FileRoutesByTo {
  '/nilus': typeof NilusRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/$threadId': typeof ChatThreadIdRoute
  '/chat/landing': typeof ChatLandingRoute
  '/nilus/changes': typeof NilusChangesRoute
  '/nilus/chat': typeof NilusChatRoute
  '/nilus/evidence': typeof NilusEvidenceRoute
  '/nilus/memory': typeof NilusMemoryRoute
  '/nilus/settings': typeof NilusSettingsRoute
  '/nilus/tasks': typeof NilusTasksRouteWithChildren
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/': typeof ChatIndexRoute
  '/nilus/tasks/$taskNumber': typeof NilusTasksTaskNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/nilus': typeof NilusRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/_chat/$threadId': typeof ChatThreadIdRoute
  '/chat/landing': typeof ChatLandingRoute
  '/nilus/changes': typeof NilusChangesRoute
  '/nilus/chat': typeof NilusChatRoute
  '/nilus/evidence': typeof NilusEvidenceRoute
  '/nilus/memory': typeof NilusMemoryRoute
  '/nilus/settings': typeof NilusSettingsRoute
  '/nilus/tasks': typeof NilusTasksRouteWithChildren
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/_chat/': typeof ChatIndexRoute
  '/nilus/tasks/$taskNumber': typeof NilusTasksTaskNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/nilus'
    | '/settings'
    | '/$threadId'
    | '/chat/landing'
    | '/nilus/changes'
    | '/nilus/chat'
    | '/nilus/evidence'
    | '/nilus/memory'
    | '/nilus/settings'
    | '/nilus/tasks'
    | '/settings/archived'
    | '/settings/general'
    | '/nilus/tasks/$taskNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/nilus'
    | '/settings'
    | '/$threadId'
    | '/chat/landing'
    | '/nilus/changes'
    | '/nilus/chat'
    | '/nilus/evidence'
    | '/nilus/memory'
    | '/nilus/settings'
    | '/nilus/tasks'
    | '/settings/archived'
    | '/settings/general'
    | '/'
    | '/nilus/tasks/$taskNumber'
  id:
    | '__root__'
    | '/_chat'
    | '/nilus'
    | '/settings'
    | '/_chat/$threadId'
    | '/chat/landing'
    | '/nilus/changes'
    | '/nilus/chat'
    | '/nilus/evidence'
    | '/nilus/memory'
    | '/nilus/settings'
    | '/nilus/tasks'
    | '/settings/archived'
    | '/settings/general'
    | '/_chat/'
    | '/nilus/tasks/$taskNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  NilusRoute: typeof NilusRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  ChatLandingRoute: typeof ChatLandingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nilus': {
      id: '/nilus'
      path: '/nilus'
      fullPath: '/nilus'
      preLoaderRoute: typeof NilusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/nilus/tasks': {
      id: '/nilus/tasks'
      path: '/tasks'
      fullPath: '/nilus/tasks'
      preLoaderRoute: typeof NilusTasksRouteImport
      parentRoute: typeof NilusRoute
    }
    '/nilus/settings': {
      id: '/nilus/settings'
      path: '/settings'
      fullPath: '/nilus/settings'
      preLoaderRoute: typeof NilusSettingsRouteImport
      parentRoute: typeof NilusRoute
    }
    '/nilus/memory': {
      id: '/nilus/memory'
      path: '/memory'
      fullPath: '/nilus/memory'
      preLoaderRoute: typeof NilusMemoryRouteImport
      parentRoute: typeof NilusRoute
    }
    '/nilus/evidence': {
      id: '/nilus/evidence'
      path: '/evidence'
      fullPath: '/nilus/evidence'
      preLoaderRoute: typeof NilusEvidenceRouteImport
      parentRoute: typeof NilusRoute
    }
    '/nilus/chat': {
      id: '/nilus/chat'
      path: '/chat'
      fullPath: '/nilus/chat'
      preLoaderRoute: typeof NilusChatRouteImport
      parentRoute: typeof NilusRoute
    }
    '/nilus/changes': {
      id: '/nilus/changes'
      path: '/changes'
      fullPath: '/nilus/changes'
      preLoaderRoute: typeof NilusChangesRouteImport
      parentRoute: typeof NilusRoute
    }
    '/chat/landing': {
      id: '/chat/landing'
      path: '/chat/landing'
      fullPath: '/chat/landing'
      preLoaderRoute: typeof ChatLandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/$threadId': {
      id: '/_chat/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/nilus/tasks/$taskNumber': {
      id: '/nilus/tasks/$taskNumber'
      path: '/$taskNumber'
      fullPath: '/nilus/tasks/$taskNumber'
      preLoaderRoute: typeof NilusTasksTaskNumberRouteImport
      parentRoute: typeof NilusTasksRoute
    }
  }
}

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface NilusTasksRouteChildren {
  NilusTasksTaskNumberRoute: typeof NilusTasksTaskNumberRoute
}

const NilusTasksRouteChildren: NilusTasksRouteChildren = {
  NilusTasksTaskNumberRoute: NilusTasksTaskNumberRoute,
}

const NilusTasksRouteWithChildren = NilusTasksRoute._addFileChildren(
  NilusTasksRouteChildren,
)

interface NilusRouteChildren {
  NilusChangesRoute: typeof NilusChangesRoute
  NilusChatRoute: typeof NilusChatRoute
  NilusEvidenceRoute: typeof NilusEvidenceRoute
  NilusMemoryRoute: typeof NilusMemoryRoute
  NilusSettingsRoute: typeof NilusSettingsRoute
  NilusTasksRoute: typeof NilusTasksRouteWithChildren
}

const NilusRouteChildren: NilusRouteChildren = {
  NilusChangesRoute: NilusChangesRoute,
  NilusChatRoute: NilusChatRoute,
  NilusEvidenceRoute: NilusEvidenceRoute,
  NilusMemoryRoute: NilusMemoryRoute,
  NilusSettingsRoute: NilusSettingsRoute,
  NilusTasksRoute: NilusTasksRouteWithChildren,
}

const NilusRouteWithChildren = NilusRoute._addFileChildren(NilusRouteChildren)

interface SettingsRouteChildren {
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  NilusRoute: NilusRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  ChatLandingRoute: ChatLandingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
